spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

#server:
#  port: 8077

#scheduler:
#  fixed:
#    delay:
#      milis: 3600000

#spring:
#    jpa:
#      database-platform: org.hibernate.dialect.PostgreSQLDialect